version: "3"

services:
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    volumes:
      - ./docs:/docs
    ports:
      - 8080:80

  dev: &dev-image
    build:
      context: .
      dockerfile: Dockerfile
    image: sovereign-note-dev
    volumes:
      - .:/src

  lint:
    <<: *dev-image
    command: |
      poetry run flake8

  test:
    <<: *dev-image
    command: |
      poetry run pytest --cov=sovereign_note

