name: Build Docs

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Documentation
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        sphinx-build -b html docs build

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: |
          build
        retention-days: 3

    - name: Create a new commit to gh-pages
      if: success() && github.ref == 'refs/heads/main'
      run: |
        # Tell GitHub pages not to use Jekyll.
        #
        # Without creating the `.nojekyll` file, GitHub Pages will treat some
        # paths differently. For example, directories starting with an
        # underscore will not be served.
        touch build/.nojekyll

        git add --force build
        git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "Apply automatic changes" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        git subtree split --prefix build -b gh-pages
        git push --force origin gh-pages

